# Generated by Django 2.1.7 on 2019-04-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='imageID',
            new_name='photoID',
        ),
    ]
