# Generated by Django 2.1.7 on 2019-04-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_emoji_photoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
