# Generated by Django 2.1.7 on 2019-04-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0006_auto_20190429_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photoID',
            field=models.IntegerField(default=0),
        ),
    ]
