# Generated by Django 2.1.7 on 2019-04-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0007_auto_20190429_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='emoji',
            field=models.CharField(default='', max_length=200),
        ),
    ]
