# Generated by Django 2.1.7 on 2019-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0008_auto_20190430_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='emoji',
            field=models.IntegerField(default=0),
        ),
    ]
