# Generated by Django 2.1.7 on 2019-05-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0009_auto_20190501_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='emoji',
            field=models.CharField(default='', max_length=200),
        ),
    ]
